version: '3.9'
services:
  backend:
    image: "michalsimon/static-website:node14"
    environment:
      S3_BUCKETNAME: images
      S3_ENDPOINT: http://s3:9000
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: toor1234
      ENV: dev
    working_dir: /backend
    volumes:
      - .:/backend
    ports:
      - "5000:5000"
    links:
      - s3
    depends_on:
      - s3

  s3:
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: toor1234
    entrypoint: sh
    command: -c 'mkdir -p /data/images && minio server /data --console-address=0.0.0.0:9001'
