parameters:
  config.path: /../config/config.yml

services:
  # Components
  configurator:
    class: 'components/Configurator'
    arguments:
      - '%config.path%'

  version:
    class: 'components/Version'

  s3Connection:
    class: 'components/S3Connection'
    arguments:
      - '@configurator'

  rekognitionConnection:
    class: 'components/RekognitionConnection'
    arguments:
      - '@configurator'


  # Controllers
  healthCheckController:
    class: 'controllers/HealthCheckController'
    arguments:
      - '@version'

  analyzeController:
    class: 'controllers/AnalyzeController'
    arguments:
      - '@imageModel'
      - '@sentimentModel'

  # Models
  s3Model:
    class: 'models/S3Model'
    arguments:
      - '@s3Connection'

  imageModel:
    class: 'models/ImageModel'
    arguments:
      - '@s3Model'
      - '@configurator'

  rekognitionModel:
    class: 'models/RekognitionModel'
    arguments:
      - '@rekognitionConnection'

  sentimentModel:
    class: 'models/SentimentModel'
    arguments:
      - '@rekognitionModel'
