parameters:
  config.path: config/config.yml

services:
  # Components
  configurator:
    class: 'components/Configurator'
    arguments:
      - '%config.path%'

  version:
    class: 'components/Version'

  # Controllers
  healthCheckController:
    class: 'controllers/HealthCheckController'
    arguments:
      - '@version'

  testController:
    class: 'controllers/TestController'

  ManipualteDataController:
    class: 'controllers/ManipualteDataController'
